openai:
    model:
        completions: ${OPENAI_MODEL_COMPLETIONS:gpt-3.5-turbo-instruct}
        chat-completions: ${OPENAI_MODEL_CHAT_COMPLETIONS:gpt-3.5-turbo-16k}

    api:
        key: ${OPENAI_API_KEY} #Add your own key. Generate it here https://platform.openai.com/api-keys
        url:
            completions: ${OPENAI_MODEL_COMPLETIONS:https://api.openai.com/v1/completions}
            chat-completions: ${OPENAI_MODEL_CHAT_COMPLETIONS:https://api.openai.com/v1/chat/completions}

---
#Add your own key. Generate it here https://platform.openai.com/api-keys
#This config is for spring AI
spring:
    ai:
        openai:
            api-key: ${OPENAI_API_KEY}